language: node_js
node_js:
  - "7"
cache: yarn
script: yarn run test:ci
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master